sudo: required

language: 
  - python

python:
    - "3.6"

install:
    - "pip install coveralls"
    - "pip install pytest-cov"
    - "pip install --no-cache-dir -r requirements.txt"

script:
    - "make test"

after_success:
    - coveralls