sudo: required

language: 
  - python

python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - "pip install coveralls"
    - "pip install --no-cache-dir -r requirements.txt"

script:
    - "make test"
    
after_success:
    - coveralls