sudo: required

language: 
  - python

python:
    - "3.5"
    - "3.6"

install:
    - "pip install --no-cache-dir -r requirements.txt"
    - "pip install --no-cache-dir -r requirements_dev.txt"

script:
    - "make test"
    - "make format"

after_success:
    - coveralls